name: Flutter Docker Image CI

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set docker tag from version.properties
      run: cat version.properties >> $GITHUB_ENV
    - 
      name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/flutter:$release_tag-stable
    - name: push to registry
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flutter:$release_tag-stable
